

on:
  push:
    branches:
      - add-custom-command-workflow
  workflow_dispatch:
    inputs:
      command-to-run:
        description: Command to run
        required: false
        default: |
          Rscript -e 'cat("test1")'
        type: string
      artifact-wildcard:
        description: Artifact wildcard
        required: false
        default: '*.html'
        type: string

name: Custom command runner

jobs:
  custom-command:
    runs-on: ubuntu-latest
    container:
      image: rocker/r-base:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run command
        run: |
          ${{ inputs.command-to-run }}
        shell: bash

      - uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: ${{ inputs.artifact-wildcard }}

