---
name: Debug

on:
  push:
    branches:
      - debug

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: |
          apt update && apt install -yq curl
          curl -vvv https://pharmaverse.slack.com

  spelling:
    name: Spell Check 🆎
    uses: insightsengineering/r.pkg.template/.github/workflows/spelling.yaml@main
