---
name: Debug

on:
  push:
    branches:
      - debug

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: |
          curl -vvv https://pharmaverse.slack.com

  links:
    name: Check URLs 🌐
    uses: insightsengineering/r.pkg.template/.github/workflows/links.yaml@main
